app = "darwing-langbot"
primary_region = "hkg"

[build]

[http_service]
internal_port = 5300
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
method = "GET"
path = "/"
interval = "30s"
timeout = "10s"
grace_period = "10s"

[[services]]
internal_port = 2280
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2280

[[services]]
internal_port = 2281
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2281

[[services]]
internal_port = 2282
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2282

[[services]]
internal_port = 2283
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2283

[[services]]
internal_port = 2284
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2284

[[services]]
internal_port = 2285
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2285

[[services]]
internal_port = 2286
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2286

[[services]]
internal_port = 2287
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2287

[[services]]
internal_port = 2288
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2288

[[services]]
internal_port = 2289
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2289

[[services]]
internal_port = 2290
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 2290

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[mounts]]
source = "langbot_data"
destination = "/app/data"

[env]
TZ = "Asia/Shanghai"

[processes]
app = "uv run main.py"